Fix build (maybe due to GCC 4.7?)
/builds/grive-git/src/grive/libgrive/src/http/Agent.cc: In function ‘void {anonymous}::CallbackInt(int)’:                                      
/builds/grive-git/src/grive/libgrive/src/http/Agent.cc:63:2: error: ‘cout’ is not a member of ‘std’